language: node_js
node_js:
  - "10"
install:
- npm install -g travis-ci-cloudfront-invalidation
- npm install
script:
- npm run test
- npm run build
before_deploy:
- cd build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: "juancastillom.com"
  endpoint: "https://s3.us-west-1.amazonaws.com"
  skip_cleanup: true
  region: "us-west-1"
  acl: public_read

after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -o 'master,stage'