language: node_js
node_js:
  - "node"
install:
- npm install
- npm rebuild node-sass
script:
- npm run test
- npm run build
before_deploy:
- cd build

deploy:
  provider: s3
  access_key_id: "AKIAIIDZXLPGRUOMZ6OA"
  secret_access_key: "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"
  bucket: "juancastillom.com"
  endpoint: "https://s3.us-west-1.amazonaws.com"
  skip_cleanup: true
  region: "us-west-1"
  acl: public_read